---
- name: Ensure CCC Pis are configured the same
  hosts: all

  tasks:
  #- name: configure wayfire.ini for auto start
  #  ansible.builtin.lineinfile:
  #    path: /home/catfordcc/.config/wayfire.ini
  #    line: '[autostart]'
  #    create: yes

  #- name: adding chromium startup lines to wayfire.ini
  #  ansible.builtin.blockinfile:
  #    path: /home/catfordcc/.config/wayfire.ini
  #    insertafter: '[autostart]'
  #    state: present
  #    block: | 
  #      chromium = chromium-browser https://www.raspberrypi.org/learn/ --noerrdialogs --disable-infobars --no-first-run -ozone-platform=wayland --enable-features=OverlayScrollbar --disable-restore-session-state --start-fullscreen
  #      chromium2 = chromium-browser https://scratch.mit.edu/ --noerrdialogs --disable-infobars --no-first-run --ozone-platform=wayland --enable-features=OverlayScrollbar --disable-restore-session-state
  #      screensaver = false
  #      dpms = false
      
  - name: delete the wayfire.ini as it creates errors
    ansible.builtin.file:
      path: /home/catfordcc/.config/wayfire.ini 
      state: absent
 
  - name: adding catford CC packages
    ansible.builtin.apt:
      pkg:
        - git
        - python3-configobj
        - python3-send2trash
        - python3-dropbox

  - name: Install python packages
    ansible.builtin.pip:
      name:
        - pgzero
      break_system_packages: true

  - name: clone drupebox
    ansible.builtin.git:
      repo: https://github.com/duncanhawthorne/drupebox.git 
      dest: /home/catfordcc/drupebox
      clone: yes
      update: yes

  - name: Remove the old cron tab job that ran as sudo that didn;t work
    ansible.builtin.cron:
      name: "drop box sync"
      state: absent

  - name: Ensure a cron job exists to create the dropbox sync every minute. Creates the entry "0 5,2 * * ls -alh > /dev/null"
    ansible.builtin.cron:
      name: "drop box sync"
      user: catfordcc
      job: "/usr/bin/python3 /home/catfordcc/drupebox/drupebox.py"

  - name: ensure that firefox is the default browser
    ansible.builtin.shell:
      cmd: update-alternatives --set x-www-browser /usr/bin/firefox #/usr/bin/chromium-browser
