---
- name: update and upgrade Pis
  hosts: all
  gather_facts: false

  tasks:
  - name: update and upgrade
    become: true
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One Day

  - name: Remove dependencies that are no longer required
    become: true
    ansible.builtin.apt:
      autoremove: yes
      purge: true

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes
